### PR TITLE
WR-249

### PR DESCRIPTION
**Pull request by hbeachey**
Reworking some of the web reno test code, actual tests that require login wont work until we set up shibboleth as currently we're not using OIT's CAS but the library internal CAS that doesn't have the test accounts configured.

### CODE REVIEW

**Comment by h-parekh** [comment]
Before we merge this into master I'll need to review these for consistency with the rest of the tests.

**Comment by h-parekh** [comment]
@hbeachey - I don't want to merge this pull request until you get a chance to test it against OIT's CAS.

**Comment by hbeachey** [comment]
@h-parekh I've been unable to get their CAS to work, perhaps I'm doing something wrong but it seems I'll need to contact them to set it up. I'll discuss with Rob tomorrow about what we want to do.

**Comment by jeremyf** [comment]
ping @hbeachey and @h-parekh

**Comment by h-parekh** [comment]
Based on my conversation with @hbeachey last week, we're expecting CAS login issues to be remediated in this sprint. Perhaps we should close this PR and reopen at a later point?

**Comment by jeremyf** [comment]
Go ahead and keep this open.

**Comment by h-parekh** [comment]
@hbeachey - did you have any work on your local branch that hasn't been pushed yet?

**Comment by hbeachey** [comment]
No, before any tests can be written we need a way to get test data in those accounts so that's what I've been working on instead.

**Pull request merged**
